### ISSUE TITLE
@Transactional 어노테이션 관련

### ISSUE THREAD

**Issue by JoshWPark** [JoshWPark/board#1]
지금 제가 BoardService의 updateBoard 메서드를 @Transactional 어노테이션을 사용해서 풀었는데, 혹시 다른 방법이 있을까요?

**Comment by slsnrnsep** [comment]
안녕하세요 우현님! 착오가 있어서 리뷰를 늦게 답변드리는 점 우선 죄송합니다. 

질문 주신 @transactional 어노테이션을 사용하더라도 정상 응답이 나가는 것을 확인하실 수 있으실 겁니다. 
트랜잭션 어노테이션은 푸는 다른 방법이 존재하는게 아니라 사용할거냐,안할거냐 를 선택할 수 있다가 답변이 될 것 같습니다.

트랜잭션 의미 자체는 데이터베이스의 상태를 변환시키는 하나의 논리적 기능을 수행하기 위한 작업의 단위 또는 한꺼번에 수행되어야할 일련의 연산들입니다.

쉽게 풀어보자면, JPA에서 쿼리를 생성하여 실제 RDB와 통신하는 일련의 과정을 하나로 묶은 단위라고 생각하시면 될 것 같습니다. 물론 공부는 더 많이 하셔서 블로그에 정리하신다면 더 좋은 경험이 되실 것 같습니다.

특징으로는 @Transactional 어노테이션이 걸려있는 메서드의 경우, 로직 중간에 예외가 발생하더라도 DB에 실제로 수정이 되지 않습니다.
```
Post post = new Post();
postRepository.save(post); //post를 먼저 Save시킴

throw new IllegalArgumentException(); //save시킨 후 예외가 발생함
```
일반적으로 생각하기에 코드는 위에서 아래로 진행되므로 save가 먼저되고 예외가 발생한거니, DB에는 저장되었을 거라 생각하시는게
보편적입니다. 실제로도 트랜잭션 어노테이션을 사용하지 않으면 똑같은 로직 수행시 DB에는 저장됩니다.

그러나 트랜잭션 어노테이션을 사용한다면 DB에 save를 시킨 뒤, 예외가 발생한다면 JPA에서는 save하는 쿼리를 날리지 않습니다. 
따라서 DB에도 저장이 되지 않습니다. 이처럼 로직이 복잡할수록 혹시 모를 예외가 발생시에도 메서드 전체가 예외없이 종료되기 전에는
DB에 실제 쿼리를 보내지 않는 특징을 가지고 있습니다. (조금 더 안전한 코딩을 할 수 있겠죠?)

따라서 서비스의 모든 메서드들에 대해서는 트랜잭션 어노테이션을 모두 사용하는 것을 권장드립니다.
그러나 조회만 있는 로직이라면 읽기전용 옵션을 사용하시는게 좋은데, 왜 좋은지에 대해서는 꼭 공부해보시길 바랍니다.
@Transactional(readOnly = true)

**Comment by JoshWPark** [comment]
답변과 섬세한 정보에 감사드립니다!
