### ISSUE TITLE
Level2 까지의 코드 리뷰 안내드립니다.

### ISSUE THREAD

**Issue by slsnrnsep** [JoshWPark/board#3]
-BoardController
@RequestMapping("/board") 으로 한번 묶은 상태에서 @PostMapping("/post") 를 하시게 되면 /board/post 로 호출하게 되는데 Restful 하지 못한 것 같습니다. Restful API 에 대해서 검색해보시고 누가 보더라도 url만 읽었을떄 어떤 행위를 하는 API인지 쉽게 알아야 프론트엔드와의 소통이 더 수월하겠죠?

***
-UserController
@valid 사용하여 유효성 체크하신 부분 잘하셨습니다. 그러나 마찬가지로 /auth라는 경로가 꼭 필요한지 고민해보시길 바랍니다. 추가로 ExceptionHandler를 구현하셨는데, 각 Controller마다 중복되는 코드를 생산하는 것은 좋지 않으니, @RestControllerAdvice를 사용하여 전역예외처리를 하는 방법을 고민해보시면 좋겠습니다.
***
-Dto 패키지
Dto에 생성자가 필요해 보입니다. 왜 있어야 하는지에 대해서는 https://ksh-coding.tistory.com/48 글을 참고해보시는 것을 추천드립니다.
***
-Entity 패키지
Board의 생성방식을 of라는 이름의 정적 팩토리 메서드를 사용하신점이 좋았습니다. 하지만 인자를 requestDto에도 username이 필드로 존재하는데, 2번쨰 인자를 username으로 할 필요는 있었을까에 대한 고민이 필요할 것 같습니다.
***
-Service 패키지
이제 stream에 대해서 잘 사용하실 수 있는 것 처럼 보여 좋네요!  전체적으로 토큰을 검증하는 과정이 중복코드가 있는데 이런 경우 메서드로 뺴거나 별도의 util클래스로 생성하는게 어떠실까요? 추가로 new AuthResponseDto("게시글 삭제 성공", 200); 같은 부분은 String형태기 떄문에 많은 개발자들과 협업한다고 가정했을 때에 누구는  new AuthResponseDto("게시글 삭제 샹공", 200);  이라는 오타를 냈을 떄 문구를 "게시글 삭제가 성공했습니다" 로 바꿔야하는 상황이 온다면, 되게 찾아서 고쳐야 하는데 힘들 수 있으니 , Enum으로 관리하는 방법도 있으니 한번 시도 해보시면 좋아보입니다.

**Comment by JoshWPark** [comment]
안녕하세요 매니저님, 부족한 코드이지만, 코드 리뷰를 해주셔서 감사합니다. 리뷰에서 적어주신 사항들은 토큰 검증하는 과정을 예외하고는 다 반영하였습니다. 추후에 검증하는 과정도 반영하겠습니다.
