### ISSUE TITLE
Security Filter Chain 관련하여 질문이 있습니다. 

### ISSUE THREAD

**Issue by JoshWPark** [JoshWPark/board#5]
WebSecurityConfig 파일 내 SecurityFilterChain 메서드에서 jwt 토큰이 없어도 접속이 가능한 url들을 제가 명시해두었습니다. 
근데 만약 jwt 토큰을 확인하는 메서드에, jwt 토큰이 없을 시 에러를 던지라 정하고, .permitAll()로 지정되어 있는 url에 접속하려 하면  SecurityFilterChain 메서드에 정해둔 authenticationEntryPoint에 걸려서 에러가 발생 됩니다. 

물론 이 문제는 jwt 토큰 확인하는 메서드에  jwt 토큰이 없을 시 에러를 던지는 것을 없애면 해결 되지만, 위 방법으로 했을 떄 에러가 나는 이유를 알고 싶습니다.

**Comment by slsnrnsep** [comment]
스프링 시큐리티의 주요예외는 2가지가 있습니다. AuthenticationException 와 AccessDeniedException 2가지가 있습니다. 현재 코드에서도 
```
http.exceptionHandling().authenticationEntryPoint(customAuthenticationEntryPoint);
http.exceptionHandling().accessDeniedHandler(customAccessDeniedHandler);
```
를 통해서 주요예외를 따로 처리해주는 Custom Class를 구현하셨기 떄문에 , 발생하는 에러들은 CustomClass에서 @Override된 곳에서 처리가 될 것입니다.

기존에 만들어둔 ExceptionHandler에서 처리를 하고 싶다면, 
authenticationEntryPoint에서 @ExceptionHandler({ AuthenticationException.class }) 와, HandlerExceptionResolver 를 사용하여 기존에 만들어둔 쪽에서 처리를 하도록 위임하는 방법도 가능합니다. 
관련해서 https://velog.io/@dailylifecoding/spring-security-exception-handling-and-request-caching
에 그림이 시큐리티 예외처리에 대해 그림으로 잘나와있는 것 같아서 한번 보시는 것을 추천드립니다!

**Comment by slsnrnsep** [comment]
LV4까지의 코드리뷰 공유드립니다!
---
Controller 패키지
우선 지난번보다 Restful해진 것 같아서 코드를 이해하는데에 더 수월했습니다. RequestMapping으로 /board를 다 묶으시는데, repository 이름이 board라 묶은 것 같습니다. 의도는 이해되지만 board와 post는 같은 의미로 이해되는 경향이 있는 것 같습니다. 보통의 api 맨 앞에는 버전정보 ex)v1,v2,v3 등 api라는 뜻의 /api 등이 붙는 편인것 같아요. 다음에는 /v1/posts 라는 의미로 게시글 작성을 할 수 있어 보입니다.
/board/new 보다는 HttpMethod인 Post를 통해서 작성하는 것임을 유추할 수 있기 때문에 new라는 url은 어울리지 않는 것 같아요.
***
dto 패키지
컨트롤러의 반환값들이 BasicResponseDto로 제네릭을 사용하여 잘 정리해주셨는데, 모든 컨트롤러와 서비스단의 반환값이 BasicResponseDto이다 보니, 여러명이서 협업하다 보면 헷갈릴 수 있는 가능성이 있어보여요. 제네릭을 사용하신만큼, 
Controller에는 와일드카드를 사용한 BasicResponseDto<?> 을 반환하고, 서비스단의 메서드들에는 실제 반환하는 ResponseDto 들을 반환하도록 하고 , 일종의 utils클래스를 사용해서 깔끔하게 만들면 더 좋을것같아요. 
***
Entity패키지
Board를 생성할때, saveBoard라는 정적 팩토리메서드를 활용해서 request의 정보와 유저정보를 활용하여 새로운 Board 인스턴스를 만드는 것은 좋습니다. 그러나 앞으로 추가될 entity에도 작성자,수정한사람 등의 정보들이 계속 필요로 할텐데, 그떄마다 메서드를 활용해서 만들기 보다는 Jpa의 Auditting 기능을 활용해보는 것은 어떨까요? @CreatedBy 라는 키워드로 검색해보시면, 자동으로 jpa에서 작성자 userID를 DB에 insert될때 심어넣어줄 수 있습니다! 
***
예외처리 관련
enum으로 잘 분리는 하셨습니다. 그러나 code와 message를 따로 분리할 필요없이, enum에 필드값으로 code,msg를 선언하여 하나의 Enum으로 관리하는게 더 좋을 것 같아요. 그게 아니라면, 별도의 RuntimeException을 상속받은 CustomException을 생성하셔서 필요한 예외 정보들을 가지는 exception class들을 관리하여 예외처리하면 더 좋을것 같습니다. 지금도 물론 훌륭한 예외처리 입니다.
***
Service 패키지
한번 깔끔하게 리팩토링 한 흔적이 보이는 것 같아서 좋습니다. SuperService라는 공통의 메서드들을 묶은 점은 좋았지만, , 이렇게 되면 SuperService에서 상속받은 boardService에서 commentCheck 메서드는 BoardService에서는 사용하지 않아보이는데 1개의 클래스로 모두 관리하려고 하다보니 이렇게 된 것 같습니다. 의도는 훌륭하지만, interface를 사용한다거나, 특정한 service에서만 사용되는 메서드라면 그 service에서 private 메서드로 관리하는게 더 좋아보입니다.
***

전체적으로 지난번 리뷰당시보다 코드의 가독성과 구조가 좋아진 것이 느껴집니다. 많은 고민을 하신게 느껴지며 이제 앞으로는 배포도 하셔야 하니 application.properties 파일은 github에 올리시면 안됩니다. (DB정보나 Jwt SecretKey가 노출되어 있어요) - 해커나 장난치는 사람들이 repo를 검색하여, aws 폭탄요금을 부과하게 한다던가, 시크릿키가 노출되어 관리자가 아님에도 여러 기능들을 수행하도록 하면 안되겠죠?
간단하게는 gitignore에서 처리가 가능하고, 암호화하는 jasypt라는 라이브러리도 있으니 검색한번 해보시면 좋을 것 같아요.

**Comment by JoshWPark** [comment]
코드 리뷰를 해주셔서 감사합니다. 리뷰에서 적어주신 사항들은 Entity 패키지 부분을 예외하고는 다 반영하였습니다.  감사합니다.
